apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: ghcr.io/price-tracker/backend:20230511135818-da54277 # {"$imagepolicy": "flux-system:backend"}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PORT
              value: "80"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend
                  key: psql-connection-string
      imagePullSecrets:
        - name: ghcr
