apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend
  namespace: price-tracker
spec:
  encryptedData:
    jwt-secret: AgC/OhwzzbHf5xh2X0sGfVDffL2fvebBMdaS16Aos/EXHoMhpYLeCcGIvoGv8Mu7QNFR/T/L4Lwwz2XMo/JLJPZmyumNfP214sh30myjkTlzWCHBgGMCuvcMmuQHJ0T6smOca0DQ5lrPjWqN4B/9wqbA8vfkzf7jLX/EoshG7E4qHuqEHIcy3oQm0lGS6QwxYRyVFGzBJN22q/ylQHX+Fqq8HG+x/LOaaZgcUXLkPFxIoClqYx/FuByu1EM3i/t3vK5qg/dWvXq+zbtRR7qjjBq2RF1gsTXhtjMJJzJsVS1UZaercmtHXpwMcRKbW2OWdElcM3P6h5NyKtxY1j2jVXWkqoD1JYxodJnZ9YTQMLtX+bRT/NdYLLp/9UxwRSkOuDTjZOIiVyGe77uyUXIeELnXz2ZdwFbDJX022axONhXHdocedENx1P0m95Br/UqdPZ5K1Q/THm4j6wwLAkrikFkHYT7pvYRWemc4ygWdAIVt4S1fMvV9wwZPsJQZrOwygtjviXkbI71dFilDUw1ifhVWRwjjbYovLy8rSfhA0Isuqda990yfc+REjMu15gmX3pyLBSScyt4/u2NytxV46bT4lrkSZHe/pSSTNmR5cx/yIinxN+BbHmH5d5Nd1TsGbD0+ELmu1R9MmHjZHnjJGMhI7wzWU9NsF8icfnrE1jl0CgIHfhEW94a/9QthO4YqWGqCVtOYIqi5+RMOAS2byO8YEdptRzq5grDOzN01f4g3gA==
    psql-connection-string: AgBOs8kGMpLfZ3rT5rjtOppaCZImzXGMS5/vMlvZ58XkfeFxPwS0PFeWNgUHklHEokJqiJyTPrXKsHs+nj/V6t3RheM4JvCgb81NgZBWO6OYjbNDYyczVZnr6/Pid/zRqR9kTDEWCEKfkgFwkMoUoSBpl3dT3vs36U9lkmEAIzczSOQ04ZvoWTJQ1BJ7yT2isdl9sluHPkm+/FTqYv1kn0wUryGeGOEdW38GYxYrh6/jDC3IEMEUnuB89VoeIbUC+zkg0E2XOGeryUYUkJ65Z08j4yjeowPaqRnlWf0RmK+JXtUy37Hl04hw8YM6PrIp3SdMdCI6jxJVm8I6JSjGnfie0VyJNl3IJ+UQ/oWWMSyVDL3VuKLdSHblT9gs/kL/VkKg0KOsXkKKAYrwrl7BUGi2URNttYvMQv3Szcmm5YjoLiNkBJKLSV7RcBCRQSYOrJB3WtWUwNwdcXguXvCynq40o9IWY5J8EaVa/7Ve52JWXnxn5Ira1KRCFjLQc+iGXLMtI//Rv93RahS+xhDQtjvwHT1zplY+7ySf2PD5cBZ7cj3nZHsBWt1I2l6b/jPY9YQ5LysROK8ycAln16olB9n0C48nNO2mUo/iPX0kInY7F9y7P7H83GMTnIkZfFWQxGDBNbLQ4QxSJrx335rwTymTjECYq0TQjF2AolAMB53xOT4KUekDtthtCFxW/Y4pJc0a2DTFXrZHSNuf5LiG/VvdReMolEqnqJSKWQvwrUxq53Nvjga9/Fe7NzJAI1lMLudnuBWrYiUSy5TlJumHvAncusWxvw==
  template:
    metadata:
      creationTimestamp: null
      name: backend
      namespace: price-tracker

