apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend
  namespace: price-tracker
spec:
  encryptedData:
    jwt-secret: AgBK+yn7xwwYSeKxN43b1SBTbYBnwex8nMxvMl39KdZ44w6LRieaHxhTyaqU2Qd1G82rlCZFA5cLq6Th2AMwkULg/YpYKftuGWwRN//VSTSbaW9veup9yfCpOfWkMjPbURYVEaYFzFWzrHnXFzSE0bMPHFFKX2Xa6BSgJpLaBFlAXoE1CGaEGuSBLdKlTsLGLyJxQEwpqOZVceD8IuSTt8M76TU1DWANdeAyWFfztOuFUaMFTnAUMIpUSRu6mVmPkb9mWIZZ/3XPvJo5tQAL3loT3qVRts2xV+M3bP2kv5UhgqkGp1wBiDDw7HfA9HUiqtcqLQiaZv8ABmP3vz73abBFICifj4Eq85sf06LFjzJYWhvMmaXgwy/i6wc6o6qyJSXYpexsfOgRJ7fviLAVvvefBeeZE3BrxWg/oafiApkb6tDAFjEKAfXxO9WSZn8ayZW/KtRta642J8paxLyBB45hohFZDVlq2jjtZRCv4YQg29W5wG6ogTgt9Di0V9+s1wjkyMaP8Y1iR3p0gE7h/HPb3mXvrckngE9wpCEgvOIiMeC5j0sBvKxPgaE7dz7UVGokb8pJwcmiHf9ZUwtkAclwZNDT+2X33jDd3cBDdU7Ca2G/niKnOc4SxmFLa2F2TkmXkHuFNyOt4ApLs+AvCrVPNN/A/6bQIZUzxXAZVP8OyGp0Y3HQ30jpGps1IXCx4eFb/MwYAyssmzWr3cRQHZ9QDVZ7JYsa4dDVk0hpXWV0sw==
    psql-connection-string: AgAalkC74p3gPiSqEhYwbdTnyfArFaJhPAFtkr2eOBPt5PRsTGcXtlRlpavIqyiubvNHVwMzAUhjc3n81gwPy0dzDiKr0MNWIY6VlT4kMoP3+T5xmPTaTN57LgBrXHOk4JQK0+p6i02Vfvcy/4EEGJ6sWf3USL64uwT4GARXYfNJPTRBFEkPfpQyoM0djLgT+a0OsFhZfTL7EHabDOyLWmommlTN/igidWEtfYLTUBoTSBrxvXSt+bI5eoLc2+ptVOYthPsmFLl89nP4Nc4+DiQDeSkgVS5MGUbNvHtCTfjIKVPGq4vbEjnM2nRVd9gQJmLsoPIcwMjDd5rp1gRF7tqo/k+Amz26G/RgtU47+bnccWQKUPHXIQcmzEf+AQAH8RAJHoyGGNpxFXjw9gEjjT23G9Odvxji86ADhumywDDK8qa4DEn1IK6kQ9A2M1dwtFhb6edBGgWCDGrw30L0IZVtuBViSFM9tgUXt+XMwvOxGD1zWx6hqrpXewnURvZnOBsczGY5aWt135brTX84Qo20zFeRVmweBQQ4USUajaG2xL+SNBhmnPY0Vg7cZN6+qIbvbloc6WXB1HGiaSUyePByvuqViTrMZUnk/HIm1atxNNVLrrGfsK72Z1IkhVSoWqlBP/+5cmGNu8k30BX4AgYpl73EhaeIU6nkdWzFL2u0P/EhNNP/l+ELC88fOPQb8T0Wd9D5YCiJr5aSoVK15JxoLqyQRNDO7ypJ4Oxygdd4xlk+zF3p7G5z1GpLTB30x/YqkL+E+m8CZUtT2v94PBREMcoxaw==
  template:
    metadata:
      creationTimestamp: null
      name: backend
      namespace: price-tracker

