apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgArxawArGMWm1vQLg/N0cRu5w2PW6VCcNjz6H2yWLcf6KSYxlnC05LDzp8BAl7VW8bcWFUcvcupOfbjtdn9S5UclcXtQ1e1LuTAuY9ye5XbsUaqrYOPvnXu7CnuY1lMf5xQFNQyY6lv2LDo6ip5ATug2y3X8GX424rJ9SqTsbPeobGY+O7OoLwdNBPp64arBq4ZPLCN+7kJymqT1WZd5kG3ApfV2TVo8o1TaFGAoO5AbvKXsMzmlFopUwx9uzs57Zqd3OUjPyD0JF82RA7AGxMeBpLnXTHuGMDqbeM9ZmOzhoWKhKO9+8H8nB//JnVyn8LZWkNLGYCF3mZcOzrzrrd/XCJaWpKwwiFPAazMMaLMKdb4hvDUGCO46IJiwRg3lX96+U1J6JNIEdECd3crLcO1FdE12//JihyEg2w90XWluLvv58IwfXpOhC6Xm8IH6bsmeBh1QYlo75dDN0yx4zEu3ejvt7nW8raXHwr8N7r06UAQU8Ia96dfxXA8a1t9ykkY0III4G+8QIYU71qvMGRp8Dr1XnKkpdcV82cdEJ4sjNhnu9i1s6wSppKQ7gr9YfZrEJrVOQrE64FUwN/UUQCtQI7erR6IrmsDB07dgxvgKe7rP/wfRNtJvH24xQNeEkxKN7RcpPcz08d9aumtedAlYS1jk8qjCavK4GAN2p2cHMKki1pbZZ8BXKNDIc2pAIvTg92hNVsIbnTUqwy9ClFYB+SMMyFFym0WpunK+4Tcqj2K2WINXhM+tGu3LqGPJHguivKRzw2YAJ2Zxuf2ln56I2johX+BOGgX4Fy3b87J1UqZ1hGQj2b220AGOTnEBJDiVgE7Kgu/ovb/uQlQUNsrZVIcpopodtN0tqA1Xb7T2VQakeaLVQLBpoLhLeitIJg5DvZhrwA0weQy4JzBmAPMsA8MNsI9d6Eaa9UEt9I=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

