apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCf2L44LJjrRxmNqU8hz1TuEd02yuUEurxy5lvLb2HzUp0/Qnm3vGz5e/avM64Ad9GKcfFUdXT89RgUZtWsiguHflxOR9AAMQoy4Y9Ep5imPCp7cgMKqI6E+5dQ8E8VOHc4CVjZnN0boNc6OCtHvB0Eat82o1Kp/FqXJQKMtCHCIfZojc5VoCUoYwtzTIhyX23viFcBvEL/m9O99nDvN8NInzcZM5bL/Cb9g23HNGKapHVB9S7MuO36CkOWmMV3nVx0HZfUhnTMR0UmExT4cuovBuLkefs6Ec5vMNriqI9ESydszUWVv730bCw5FmrvkiiycqlcSc2BtHG2KgADPciNMfMMzT6tAjh3k8ybMy8iY0b1VMB8322Ly7z27mP7SN4G2yzxR/OFk4pKwtSvCC4sJImJGAaBsR4AsJ4nRbnPJEglTBvbaJt8iqnwuPSDO42RMCfkw0+Z+ZtNmXgjNAPRTt7CaewgKYthujjTgk2RZcZHOduxriPd/qBV2WyzJ20yOhAh/x3ustI07HtMXxBwxz19VGOTtB/rHCvq7ofionLAbTmozb+ZmLm57dksHa1IttcwCxfjdygVI1wS0QCMHhBKJ84uEhT49C7iFRXNWGKC1se67q3TGGxw4G5RRG6cLvFby/L6IEztkOk1gxGrHd8yHhd9qd9Qgtg59yE0c/3oqikalIDWu/oJpwKcQk8uvkQISzaLij0XS2kWD8MncJeGOSF52jlzHM5rw4XJuORQLjTjoZNs
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

