apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAK51jA2Km34iPXhp57mcItlIgXFjnomFL0Ht8LfZM37lQpwaOcNkz9H95LDCtHGdxd/qT/huWvNynqiWh5F4R2V7UYKVtUZOouJiLPdL4aAGWWobA8HGLyCmLYMai9u8pQ1iiQ3FOF1A5VE6uFPvNlCuy/itgP8OQxtPJHzwJlUUnhhtD2RdKBfkeMN97QSsoK3N+l8j/Fh7AEdXEeKk56Tb8qT+J+q3i5ZHfBcqAQAYCnYHjHfO6t4BFbOW8oIWsTEp25EFFd+EsudAvuASZsjKKUVaID017/Ay85TRerkRij9c6fH0b52X3P6ac6Z7FfraPLPaH2NMBafrA/5/uGINow3GNl6NPtDOgS6jAPH7b1KZ1/WazMMgc6som+AbznmD0dcSc1tbHf61Vapl5qHOnH46lPW2DhT3p4+rHZAxAfGelAzW08Po0Gkgsudt5/AjigmG8pi7IzrYOSIFILfPewQekMrKFHBfIoytKGNuNyFnBfveJCTKGWQOwnw8FjjRPnn7VtE+S35Y7pgtcWwzk+KYdaM+Hw1r5It0Mb1HEgOciRagcLEYWzAgRC2CZmSepwsDYDrsAi6MGvnZmPA3x0lWpY817zXFNjTeFhh1sZoXslmACOMWU+VFsWdGGjyh3KjHfgaWeuq7tFYO0ghkmZpYB5JCTrvK4gxdjfn/11bMsDNMMukxa1vIMPBxAA85BNVwCnrFs8gszE72lolBgJzTeHOwEAq261ltnnlBy/u8POBnYC
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager

