apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: price-tracker
spec:
  encryptedData:
    .dockerconfigjson: AgAqeoqlzoO0p9Uoh2SlCBdM43wonyQupMFYxpPPVBtH3heZdanV2Yl6ExH1vueYrH610cDIZ51sJ7EJ3tb4YVDofEbP6cLohq4soY6YSpyA1ea+X8P/SRig3qYSEzBEoRQoDd91BcowRpWIuMapcn9UX/Jl9248SA3XqG2526zPrKEZ5y9X6IqK4mtfJhIEE7ic+T4JNyv2TFh0h+YVvXkA/bbktQO504WtocizB3pJut/An6ocGmwxEj0jtK+7bvTlSZvbTiF01+n9vMRGza7ktascQaIlE5lrJJp5GtGfxc302UkWb9JFBI58bKy7MZdsECU+LY8kzuVVFPlBvVdn33nGDPrQy/wL4k8w1Ri133lg2/F1RpKg3B1dkyHFORo+CUybeVDWtiFrGZCpTM3q3twC+pMJ7o+l8UKPRbxZYE6dueNlTivB+LUI5soB6XoXoR8PYVIQ8+N6AryHukgaECsQxdgCO1i3DkWvtPedyfbmosTImNV/F1D7i7RvPGG61WCRqywTGEGkSpcMpkTILiu5TWWh9cXoxJ2xGb0fPyXUVFXeMOWqxYwRWjzLXTi0jeLlLMnSvh7Rd+fvtD0/GFsk2MT1qT77mX/Eab1yFxLd7LxaMnQZD5kjX0dtTCDAdWkPFrXdwqjCJlP61t2Zew5NqJJuHBADtuoy0oc71QptBO7nC7L7yqaC1LjhUOv9ZXhqC0lIYTslq3+EEXvJeYnjSUNL8ambmJqStJkz2AvoIrQJ6ksSDTYDmWKBg+cQdKdLzfcOETsrp5H9MFwziaMPFVHL5t9xkxG+9054JEBb4GSCI0NzDZPjXlKQo+4EgaY3m0agQ1GE/gm5Q385ceKKL6K7Q81WgOJwicH5QpmXlaXBS0Y92JrlNMXbj/GOpZAC/lhK2w/dI3MVeIxABwmrQVXfR8o7DrHK
  template:
    metadata:
      creationTimestamp: null
      name: ghcr
      namespace: price-tracker
    type: kubernetes.io/dockerconfigjson

