apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBXvOumBqIEiNwdVxezXnuUUwC1asAwMaNa1Jyayr/xOXg8giAX8DQRI/MiXyvTvMxr3tLGmwptsNtoObxBSxCRXDcdxyicFc8ntS3KU28uj42oeNjOYMRh9BbD2lSJ40/N38oL9+yK+j4m3ne/pok37BFuhFe/6gSNnmDSpAIfisAKvWhyKDQeNEmlStAMCHiX777oO2VWFl8eLwpu4gYqMnChrHMeP3J+EIDqPMCw3LZLWLxCLvmunHIDNgudcaio79zZKZavWAEX3mmiNtE4eD+5wO88TI2JMTKQ9FqhAhW1o+kxgjNccrj7z6lKSg5/uB0VbwRniXP3cOiQkzC6N/EaHNRh+SQW2zQt/r0MlgEffG19R47L5lOYQa4stzp75CDqAB6bkyjNxz8xk3UZnkiO1YIDSt4bR2YnsUDXi8Slp50uF8S9MmG0XkzbsaIB/FKURucPrrZMOFWfYgp19qy4w+scZJDuNSFLs4HaHA524DS4nPl2PJRuK6ogG+4orQVBl2pl7YCFpH3HWF3I7EQgFTAfqaMGEmVh7nB9+vLyxEiFFsuAyGhyN/8UX1MaSwulxDKZUuFTB/CdGhvaiGYoxPCQPaja9TwwG+8632Nl1zSSRaeEaX6dzxrIc/sesofx3d1rfbQX38PaAVmSC1wU/Ebswd2m1cyNVbtjJynRZuLIcm8+bel+NguM4IY9oXOnhEnnOtE4ibM33DDlJ0n6rlV0PLRjPqSfMrcoeLkFv68TUZMItJg5kJlwi16ty5H3wl5X8kJy25vTCcoLCqDGYrc7Fr2crtBj5ORRoCTTjclC4CqaNE9nw5x2h5/6Jhw9KHfDVS8/cNzzzvk2FmrTl0YQQYCrZO7kcqGxKf6UhHHDWhI+AmdVObg/wMTO0rKvCuTltyMmRHVZIcWVVNPQHVqxog3u53g9
  template:
    metadata:
      creationTimestamp: null
      name: ghcr
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson

