apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: local-path
  namespace: local-path-provisioner
spec:
  releaseName: local-path
  chart:
    spec:
      chart: deploy/chart/local-path-provisioner
      version: 0.0.24
      sourceRef:
        kind: GitRepository
        name: local-path-provisioner
        namespace: flux-system

  interval: 60m
  timeout: 3m0s

  values:
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /opt/k8s/local-path-provisioner/local-path