apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      version: 4.6.1
  interval: 15m
  values:
    controller:
      service:
        enabled: false
      config:
        enable-brotli: "true"
      hostNetwork: true
      hostPort:
        enabled: true

