apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: ghcr.io/price-tracker/frontend:main-45cbecd9-1684279450 # {"$imagepolicy": "flux-system:frontend"}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: ghcr
